version: "3"
services:
   web:
     image: php:8.1.25RC1-apache-bullseye
     container_name: php_host
     volumes:
       - /var/www/html:/var/www/html
     ports:
       - 5002:80
    
   DB:
     image: mariadb:latest
     container_name: mysql_host
     volumes:
       - /var/lib/mysql:/var/lib/mysql
     ports:
       - 3306:3306
     environment:
       MYSQL_DATABASE: database_host
       MYSQL_ROOT_PASSWORD: abc#123
