apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: shared-volumes
          mountPath: /var/log/nginx
  
    - name: sidecar-container
      image: ubuntu:latest
      command:
        [
          "sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 1000; done"
        ]
      volumeMounts:
        - name: shared-volumes
          mountPath: /var/log/nginx
    
    volumes:
      - name: share-volumes
        emptyDir: {}

