apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      name: nginx-pod
  template:
    metadata:
       name: nginx-pod
    spec:
      containers:
      - name: nginx-pod
        image: nginx:latest
      
