apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-replicaset
  labels:
     app: httpd_app
     type: front-end
spec:
   replicas: 4
   template:
     metadata:
       labels:
         app: httpd_app
         type: front-end 
     spec:
        containers:
          - name: httpd-container
            image: httpd:latest
   selector:
     matchLabels:
        type: front-end