apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replicationcontroller
spec:
  replicas: 3
  selector:
     app: nginx_app
     type: front_end
  template:
     metadata:
        name: nginx-app
        labels:
           app: nginx_app 
           type: front_end
     spec:
        containers:
          - name: nginx_container
            image: nginx:latest