---
- name: if conditional
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: stapp01
      copy:
        src: /usr/src/itadmin/blog.txt
        dest: /opt/itadmin
        owner: tony
        group: tony
        mode: 0655
      when: ansible_hostname == "stapp01"
    - name: stapp02
      copy:
        src: /usr/src/itadmin/story.txt
        dest: /opt/itadmin
        owner: steve
        group: steve
        mode: 0655
      when: ansible_hostname == "stapp02"
    - name: stapp03
      copy:
        src: /usr/src/itadmin/media.txt
        dest: /opt/itadmin
        owner: banner
        group: banner
        mode: 0655
      when: ansible_hostname == "stapp03"