---
# tasks file for role/test

- name: install the latest version of HTTPD
  yum:
    name: httpd
    state: latest

- name: Start service httpd
  service:
    name: httpd
    state: started

- name: copy template file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0755

- name: change owner of file
  file:
    path: /var/www/html/index.html
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"


---
# tasks file for role/test

- name: install the latest version of HTTPD
  yum:
    name: httpd
    state: latest

- name: Start service httpd
  service:
    name: httpd
    state: started

- name: copy template file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0755

- name: change owner of file
  file:
    path: /var/www/html/index.html
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

jinja template
templates/