---
- name: Copy and Unarchive playbook
  hosts: stapp01, stapp02, stapp03
  become: yes
  become_user: root
  tasks:
    - name: Copy zip file
      copy:
        src: "/usr/src/devops/nautilus.zip"
        dest: "/tmp"
    - name: Unarchive zip file
      unarchive:
        src: "/tmp/nautilus.zip"
        dest: "/opt/devops/"
        mode: "0655"
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        remote_src: yes